### ISSUE TITLE
Recusively join lists insde maps?

### ISSUE THREAD

**Issue by howardcox** [pentzzsolt/sass-recursive-map-merge#4]
Hi, I was wondering if it was an intentional decision to _not_ recursively join lists which are inside the maps being merged?

Eg:
```
@import "node_modules/sass-recursive-map-merge/_recursive-map-merge.scss";
$test1: (
	'a': (1,2,3),
);
$test2: (
	'a': (4,5,6),
);
@debug map-merge($test1, $test2);
@debug recursive-map-merge($test1, $test2);
```

I would _expect_ to get the following from a recursive function:
```
(
	'a': (1,2,3,4,5,6),
);
```

But it just behaves the same as `map-merge` and keeps the second map's value.

I have a patch which will join two lists together if they have the same key, but if this was a deliberate design decision then I'll just fork and make my own function for this.

**Comment by pentzzsolt** [comment]
If I recall correctly, I had some issues when trying to recursively merge maps, one of which was empty.

Honestly, I did not look into merging lists much, simply because I did not need that functionality, as a result, it got overlooked, it is not a design decision. If you have any suggestions on how to make this better and more useful, you are more than welcome to open a pull request, I would be happy to discuss anything! 🙂
